Windows package for msi installer
logzio/windows-msi-installer-telegraf pull request #1
Opened 2022-06-09 17:46 UTC by resdenia

2022-06-16 08:44 UTC, Doron-Bargo requested changes
looking good, please check my comments

2022-06-16 12:00 UTC, nico-shishkin approved these changes

2022-06-26 12:42 UTC, Doron-Bargo approved these changes
lgtm please update the license

2022-06-26 12:42 UTC, Doron-Bargo commented on README.md
> +Licensed under the [Apache 2.0](http://apache.org/licenses/LICENSE-2.0.txt) License.
please update to MIT. Telegraf agent is under MIT license and we put here an instance of it.
Also I didnt notice a license attached to this pr

2022-06-26 12:55 UTC, merged